#!/usr/bin/env bash

ensure_shared_network(){
  local net="${OPENCLAW_SHARED_NETWORK:-openclaw-shared}"
  docker network inspect "$net" >/dev/null 2>&1 || docker network create "$net" >/dev/null
}

render_infra(){
  log "Generate ${OPENCLAW_BASE}/infra (pgvector + valkey)"

  local infra_dir="${OPENCLAW_BASE}/infra"
  install -d -m 750 "${infra_dir}/db-init" "${OPENCLAW_BASE}/data" "${OPENCLAW_BASE}/backups"

  cp "${REPO_ROOT}/templates/infra/db-init/01-pgvector.sql" "${infra_dir}/db-init/01-pgvector.sql"

  cat >"${infra_dir}/.env" <<CFG
POSTGRES_DB=${POSTGRES_DB}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

PGVECTOR_IMAGE=${PGVECTOR_IMAGE}
VALKEY_IMAGE=${VALKEY_IMAGE}

POSTGRES_SHM_SIZE=${POSTGRES_SHM_SIZE}
POSTGRES_MEM_LIMIT=${POSTGRES_MEM_LIMIT}
POSTGRES_CPU_QUOTA=${POSTGRES_CPU_QUOTA}
POSTGRES_CPU_SHARES=${POSTGRES_CPU_SHARES}
VALKEY_MEM_LIMIT=${VALKEY_MEM_LIMIT}
REDIS_CPU_QUOTA=${REDIS_CPU_QUOTA}
REDIS_CPU_SHARES=${REDIS_CPU_SHARES}
VALKEY_MAXMEM=${VALKEY_MAXMEM}
OPENCLAW_MEM_LIMIT=${OPENCLAW_MEM_LIMIT}
OPENCLAW_CPU_QUOTA=${OPENCLAW_CPU_QUOTA}
OPENCLAW_CPU_SHARES=${OPENCLAW_CPU_SHARES}
OPENCLAW_WORKERS_RECOMMENDED=${OPENCLAW_WORKERS_RECOMMENDED}
OPENCLAW_SHARED_NETWORK=${OPENCLAW_SHARED_NETWORK}

OPENCLAW_POSTGRES_HOST=postgres
OPENCLAW_POSTGRES_PORT=5432
OPENCLAW_POSTGRES_DB=${POSTGRES_DB}
OPENCLAW_POSTGRES_USER=${POSTGRES_USER}
OPENCLAW_POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
OPENCLAW_POSTGRES_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
OPENCLAW_REDIS_HOST=valkey
OPENCLAW_REDIS_PORT=6379
OPENCLAW_REDIS_URL=redis://valkey:6379/0

PG_SHARED_BUFFERS=${PG_SHARED_BUFFERS}
PG_EFFECTIVE_CACHE_SIZE=${PG_EFFECTIVE_CACHE_SIZE}
PG_WORK_MEM=${PG_WORK_MEM}
PG_MAINTENANCE_WORK_MEM=${PG_MAINTENANCE_WORK_MEM}
PG_MAX_CONNECTIONS=${PG_MAX_CONNECTIONS}
PG_MAX_WORKER_PROCESSES=${PG_MAX_WORKER_PROCESSES}
PG_MAX_PARALLEL_WORKERS=${PG_MAX_PARALLEL_WORKERS}
PG_MAX_PARALLEL_WORKERS_PER_GATHER=${PG_MAX_PARALLEL_WORKERS_PER_GATHER}
PG_MAX_PARALLEL_MAINTENANCE_WORKERS=${PG_MAX_PARALLEL_MAINTENANCE_WORKERS}
CFG
  chmod 600 "${infra_dir}/.env"

  cp "${REPO_ROOT}/templates/infra/docker-compose.infra.yml.example" "${infra_dir}/docker-compose.infra.yml"
}

maybe_start_infra(){
  [[ "${START_INFRA}" == "1" ]] || return 0

  log "Start infra (pgvector + valkey)"
  ( cd "${OPENCLAW_BASE}/infra" && docker compose -f docker-compose.infra.yml up -d )
  docker ps --format 'table {{.Names}}\t{{.Status}}\t{{.Ports}}'
}
